: ROOTSIZE 224 ;
: NUMFATS 2 ;
: BP-BLOCK 512 ;
: SP-FAT 9 ;
: SP-TRACK 18 ;
: NUM-BLOCKS 1880 ;
: TOTAL-SECTORS 1880 ;
: NUM-HEADS 2 ;

{ DISK-NUM
T MOV AL, BYTE [0x7C01]
NT MOV BYTE [DRIVENUM], AL
NT NEXT
N DRIVENUM: DB 0 }

{ DISK-HEAD
T MOV AX, DISKHEAD
NT FPUSH AX
NT NEXT
N DISKHEAD: DB 0 }

{ DISK-SECTOR
T MOV AX, DISKSECTOR
NT FPUSH AX
NT NEXT
N DISKSECTOR: DB 0 }

{ DISK-TRACK
T MOV AX, DISKTRACK
NT FPUSH AX
NT NEXT
N DISKTRACK: DB 0 }

{ SECTOR-LOAD
T XOR AX, AX
NT MOV ES, AX
NT MOV BX, DISK
N SECTORLOAD:
NT MOV AH, 2
NT MOV AL, 1
NT MOV CH, BYTE [DISKTRACK]
NT MOV CL, BYTE [DISKSECTOR]
NT MOV DH, BYTE [DISKHEAD]
NT MOV DL, BYTE [DRIVENUM]
NT INT 0x13
NT JC SECTORLOAD
}
{ SECTOR-WRITE }
